AY2223S2-CS2103T-T17-4/tp

src/main/java/seedu/address/Main.java

- For the sake of creating PR in upstream repo.

Add comment

---

README.md
docs/DeveloperGuide.md

*Add remaining user stories
*Add use cases
*Add NFR

Improve Developer Guide

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/task/TaskAddCommand.java
src/main/java/seedu/address/model/TaskList.java

Let's,
* make tasks save on exit of application
* fix minor name mistakes

Fix inability to save tasks

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/commands/task/TaskAddCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyTankList.java
src/main/java/seedu/address/model/ReadOnlyTaskList.java
src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
src/main/java/seedu/address/model/TankList.java
src/main/java/seedu/address/model/TaskList.java
src/main/java/seedu/address/model/UserPrefs.java
src/main/java/seedu/address/model/tank/Tank.java
src/main/java/seedu/address/model/tank/TankName.java
src/main/java/seedu/address/model/tank/UniqueTankList.java
src/main/java/seedu/address/model/tank/exceptions/DuplicateTankException.java
src/main/java/seedu/address/model/tank/exceptions/TankNotFoundException.java
src/main/java/seedu/address/model/util/SampleTankUtil.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/FindCommandTest.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

Fish Ahoy does not have function to add tanks
Let's,
* Add related Tank classes to model package

Add Tank model package files

---

src/main/java/seedu/address/logic/commands/tank/TankAddCommand.java
src/main/java/seedu/address/logic/commands/tank/TankCommand.java
src/main/java/seedu/address/logic/commands/tank/TankDeleteCommand.java

Added:
*Abstract tank commmand
*Add tank command
*Delete tank command

Add Tank Commands

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/commands/tank/TankDeleteCommand.java
src/main/java/seedu/address/model/tank/TankNameContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/tank/TankAddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/tank/TankAddCommandTest.java
src/test/java/seedu/address/logic/commands/tank/TankDeleteCommandTest.java
src/test/java/seedu/address/testutil/TankBuilder.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalTanks.java

Add Unit and Integration tests for:
*TankAddCommand
*TankDeleteCommand
Add helper utils:
*CommandUtils
*TankNameContainsKeywordsPredicate
*TankBuilder
*TypicalTanks

Create Tests for Tank Commands

---

src/main/java/seedu/address/logic/commands/fish/FishAddCommand.java
src/main/java/seedu/address/logic/commands/fish/FishCommand.java
src/main/java/seedu/address/logic/commands/fish/FishDeleteCommand.java
src/main/java/seedu/address/logic/commands/fish/FishViewCommand.java
src/main/java/seedu/address/logic/commands/tank/TankCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/fish/FishAddCommandParser.java
src/main/java/seedu/address/logic/parser/fish/FishDeleteCommandParser.java
src/main/java/seedu/address/logic/parser/fish/FishParser.java
src/main/java/seedu/address/logic/parser/fish/FishViewCommandParser.java
src/main/java/seedu/address/logic/parser/tank/TankParser.java

Currently, to add a fish we will do add tk/tank_index n/name s/species a/address t/tag
Lets refactor this by building a fish parser and fish command package
Now, you can:
1. Add fishes: **fish** add tk/tank_index n/name s/species a/address t/tag
2. Delete fishes: **fish** delete index
3. View fishes: **fish** view index

refactor add commands to fish add commands

---

src/main/java/seedu/address/commons/core/GuiSettings.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/fish/FishViewCommand.java
src/main/java/seedu/address/logic/commands/tank/TankViewCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/fish/Fish.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/ListCommandTest.java

Finish TankViewCommand and FishViewCommand

Branch view commands

---

src/main/java/seedu/address/logic/commands/task/TaskAddCommand.java
src/main/java/seedu/address/logic/parser/task/TaskAddCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/model/task/exceptions/TaskHasNoTankException.java
src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
src/main/java/seedu/address/model/util/SampleTaskUtil.java
src/main/java/seedu/address/storage/JsonAdaptedTask.java
src/main/java/seedu/address/storage/JsonSerializableTaskList.java
src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/TaskListCard.fxml
src/test/java/seedu/address/testutil/TypicalTasks.java

Tasks are independent of Fishes and Tanks
We can do cooler stuff if Tasks are related to Tanks or Fish
Let's,
* Let users assign a tank to a task when instantiating tasks
* allow creation of tasks not tied to a tank still

Add Tank attribute to Tasks

---

src/main/java/seedu/address/commons/core/GuiSettings.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/fish/FishCommand.java
src/main/java/seedu/address/logic/commands/fish/FishSortCommand.java
src/main/java/seedu/address/logic/parser/fish/FishParser.java
src/main/java/seedu/address/logic/parser/fish/FishSortCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/fish/LastFedDate.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/fish/FishSortCommandTest.java
src/test/java/seedu/address/logic/commands/tank/TankAddCommandTest.java
src/test/java/seedu/address/logic/parser/FishSortCommandParserTest.java

Fishes can be sorted according to respective parameters.
Command can be used by calling "fish sort" followed by one of the following inputs
- n
- lfd
- fi
- s
- tk

Fish Sort Command

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/task/TaskFeedingReminderCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TankList.java
src/main/java/seedu/address/model/date/DateUtil.java
src/main/java/seedu/address/model/fish/Fish.java
src/main/java/seedu/address/model/fish/LastFedDate.java
src/main/java/seedu/address/model/tank/Tank.java
src/main/java/seedu/address/model/task/Description.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/model/task/TaskFeedingReminder.java
src/main/java/seedu/address/storage/JsonAdaptedTask.java
src/main/java/seedu/address/storage/Storage.java
src/main/java/seedu/address/storage/StorageManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/Ui.java
src/main/java/seedu/address/ui/UiManager.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/tank/TankAddCommandTest.java

Lets,
* Create a new type of Task, TaskFeedingReminders
* Add them to the task list whenever there are fishes due to be fed
* Not instantiate duplicate reminders for the same tank
* Tie each reminder to a Tank

Add automatic feeding reminder upon opening app

---

docs/UserGuide.md
src/main/java/seedu/address/model/tank/equipment/Equipment.java
src/main/java/seedu/address/model/tank/equipment/EquipmentName.java
src/main/java/seedu/address/model/tank/equipment/EquipmentStatus.java
src/main/java/seedu/address/model/tank/equipment/EquipmentType.java
src/main/java/seedu/address/model/tank/equipment/LastMaintainedDate.java

add model for equipment. let me know if the model is okay or there are more fields you think are relevant to add. i will proceed with command and parser after no other inputs for the model structure

add equipment model

---

docs/UserGuide.md

add tasks priority section to user guide

add tasks priority to user guide

---

src/main/java/seedu/address/model/tank/readings/AmmoniaLevel.java
src/main/java/seedu/address/model/tank/readings/PH.java
src/main/java/seedu/address/model/tank/readings/Reading.java
src/main/java/seedu/address/model/tank/readings/Temperature.java

add model for readings. after model is okay, we will proceed with parser and commands

add model for readings

---

src/main/java/seedu/address/logic/parser/tank/readings/ReadingAddCommandParser.java
src/main/java/seedu/address/model/tank/readings/AmmoniaLevel.java
src/main/java/seedu/address/model/tank/readings/PH.java
src/main/java/seedu/address/model/tank/readings/Reading.java
src/main/java/seedu/address/model/tank/readings/Temperature.java

add reading times

---

src/main/java/seedu/address/logic/commands/task/TaskCommand.java
src/main/java/seedu/address/logic/commands/task/TaskEditCommand.java
src/main/java/seedu/address/logic/parser/task/TaskEditCommandParser.java
src/main/java/seedu/address/logic/parser/task/TaskParser.java
src/main/java/seedu/address/model/task/Task.java

* allow tasks to be edited
* can change one or more fields (priority, tank and description)

Implement task edit

---

src/main/java/seedu/address/logic/commands/tank/TankCommand.java
src/main/java/seedu/address/logic/commands/tank/TankDeleteCommand.java
src/main/java/seedu/address/logic/commands/tank/readings/ReadingsDeleteLastCommand.java
src/main/java/seedu/address/logic/parser/tank/TankParser.java
src/main/java/seedu/address/logic/parser/tank/readings/ReadingAddCommandParser.java
src/main/java/seedu/address/logic/parser/tank/readings/ReadingDeleteLastCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/tank/readings/Reading.java
src/main/java/seedu/address/model/tank/readings/UniqueIndividualReadingLevels.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/logic/commands/tank/TankAddCommandTest.java

* Add delLastReadings command
* Update tank delete command to delete Individual readings from
Full readings when called

Implement command to delete latest readings given tank index

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/tank/TankFeedCommand.java

* Deletes feeding reminder of the given tank when tank feed is called for that tank

Delete feeding reminder for tank in tank feed

---

docs/UserGuide.md

Update quick start guide and update special symbols part

---

docs/UserGuide.md

https://github.com/bokuanT/tp/blob/branch-UserGuide/docs/UserGuide.md#sorting-fishes-fish-sort

Update UG up to before fish features

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/fish/FishSortCommandParser.java
src/main/java/seedu/address/model/fish/FeedingInterval.java

Fix #217, fix feeding interval comparator

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Remove list tanks command

---

src/main/java/seedu/address/logic/commands/tank/readings/ReadingsAddCommand.java
src/test/java/seedu/address/logic/commands/tank/readings/ReadingsAddCommandTest.java
src/test/java/seedu/address/logic/commands/task/TaskAddCommandTest.java
src/test/java/seedu/address/logic/commands/task/TaskDeleteCommandTest.java
src/test/java/seedu/address/logic/commands/task/TaskEditCommandTest.java

Add tests for a few Add, delete and Edit commands for task and AddReadings

Increase test coverage

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/model/date/DateUtil.java
src/main/java/seedu/address/model/fish/LastFedDateTime.java

Our LFD parsing actually automatically changes invalid lfd to the next closest valid date. The value displayed does not match the LocalDateTime Stored
Lets,
* Display the actual local date time stored
*  Update UG about this behaviour

Change LFD display value

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/fish/FishCommand.java
src/main/java/seedu/address/logic/commands/tank/TankCommand.java
src/main/java/seedu/address/logic/commands/tank/readings/ReadingsAddCommand.java
src/main/java/seedu/address/logic/commands/task/TaskCommand.java
src/main/java/seedu/address/model/task/Description.java

* do not allow empty task desc or descriptions with all whitespace
* Fix addReadings usage message being misleading
* update command types for fish tank and task (missing edit, feed, list actions etc)
* update UG after fixed bug where tank view is done when fish is edited or added

Fix #228 and more

---

src/main/java/seedu/address/model/tank/readings/AmmoniaLevel.java
src/main/java/seedu/address/model/tank/readings/PH.java
src/main/java/seedu/address/model/tank/readings/Temperature.java

readings are now max 1d.p within their respective ranges within the graph axis

create sanity check for readings.

---

docs/DeveloperGuide.md

Add planned enhancements for #166
